version: "3.9"
services:

  php:
    platform: linux/x86_64
    build:
      args:
        user: ubuntu
        uid: 1000
      context: ./builds/php
    volumes:
      - ./src:/var/www/app
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    container_name: billion_backend
    restart: always
    working_dir: /var/www/app
    ports:
      - "9000:8000"
    networks:
      - laran
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: billion_database
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - "3310:3306"
    volumes:
      - ./builds/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - laran

  nginx:
    platform: linux/x86_64
    container_name: billion_nginx
    build:
      context: ./builds/nginx
    volumes_from:
      - php
    ports:
      - 9001:80
    networks:
      - laran

  redis:
    container_name: billion_redis
    image: "redis"
    hostname: together_redis
    ports:
      - 6379:6379
    networks:
      - laran

networks:
  laran:
    driver: bridge
